version: '3.8'

services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.15.0
    container_name: heartbeat
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    networks:
      - monitoring
  node:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: node
    environment:
      - node.name=node
      - discovery.seed_hosts=node
      - cluster.initial_master_nodes=node
      - cluster.name=cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - monitoring
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://node:9200
    networks:
      - monitoring
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - monitoring
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.15.0
    container_name: metricbeat
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge