CREATE TABLE CURSO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    creditos INT NOT NULL,
    departamento VARCHAR(30) NOT NULL
);

CREATE TABLE DISCIPLINA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    semestre VARCHAR(20) NOT NULL,
    ano INT(4),
    id_curso INT NOT NULL,
    FOREIGN KEY (id_curso) REFERENCES CURSO(id)
);

CREATE TABLE ALUNO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    turma INT NOT NULL,
    curso_hab INT NOT NULL,
    FOREIGN KEY (curso_hab) REFERENCES CURSO(id)
);

CREATE TABLE PROFESSOR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    departamento_id INT NOT NULL,
    FOREIGN KEY (departamento_id) REFERENCES DEPARTAMENTO(id)
);

CREATE TABLE DEPARTAMENTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    localizacao VARCHAR(50) NOT NULL
);

CREATE TABLE TURMA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_disciplina INT NOT NULL,
    nome VARCHAR(50) NOT NULL,
    FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id)
);

CREATE TABLE MATRICULA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_aluno INT NOT NULL,
    id_turma INT NOT NULL,
    FOREIGN KEY (id_aluno) REFERENCES ALUNO(id),
    FOREIGN KEY (id_turma) REFERENCES TURMA(id)
);

CREATE TABLE AVALIACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_aluno INT NOT NULL,
    id_disciplina INT NOT NULL,
    nota VARCHAR(5),
    FOREIGN KEY (id_aluno) REFERENCES ALUNO(id),
    FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id)
);

CREATE TABLE PRE_REQUISITO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_disciplina INT NOT NULL,
    id_pre_requisito INT NOT NULL,
    FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id),
    FOREIGN KEY (id_pre_requisito) REFERENCES DISCIPLINA(id)
);

CREATE TABLE RELATORIO_DE_NOTAS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_aluno INT NOT NULL,
    id_disciplina INT NOT NULL,
    nota VARCHAR(5),
    FOREIGN KEY (id_aluno) REFERENCES ALUNO(id),
    FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id)
);

CREATE TABLE COORDENADOR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_professor INT NOT NULL,
    id_curso INT NOT NULL,
    FOREIGN KEY (id_professor) REFERENCES PROFESSOR(id),
    FOREIGN KEY (id_curso) REFERENCES CURSO(id)
);

CREATE TABLE CARGA_HORARIA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_professor INT NOT NULL,
    id_disciplina INT NOT NULL,
    horas INT NOT NULL,
    FOREIGN KEY (id_professor) REFERENCES PROFESSOR(id),
    FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id)
);

CREATE TABLE HORARIO_AULA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_turma INT NOT NULL,
    dia_semana VARCHAR(10) NOT NULL,
    horario_inicio TIME NOT NULL,
    horario_fim TIME NOT NULL,
    FOREIGN KEY (id_turma) REFERENCES TURMA(id)
);

CREATE TABLE BIBLIOTECA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_livro VARCHAR(100) NOT NULL,
    id_disciplina INT NOT NULL,
    FOREIGN KEY (id_disciplina) REFERENCES DISCIPLINA(id)
);

CREATE TABLE ALUNO_ESTAGIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_aluno INT NOT NULL,
    empresa VARCHAR(50) NOT NULL,
    horas_semanais INT NOT NULL,
    FOREIGN KEY (id_aluno) REFERENCES ALUNO(id)
);