services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    networks:
      - app-network

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: database
    ports:
      - '5432:5432'
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3307:3306'
    networks:
      - app-network

  sqlite:
    image: alpine:latest
    command: tail -f /dev/null
    ports:
      - '3308:3308'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
